language: node_js
node_js:
  - "8"
cache:
  directories:
    "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - npm install -g gatsby gatsby-cli
  - npm install
after_success:
  - npm run deploy
